### ISSUE TITLE
Create an interface that includes a map

### ISSUE THREAD

**Issue by MichaelMale** [MichaelMale/DyfiWildlifeCentre#44]
**Story**: As a volunteer, I want to be able to view points of interest on a map, so that I'll be able to tell visitors what is around the centre.

**Brief detail**: Create an interface that includes a map, which has markers that can be added to it. the markers should link to a popup containing information about the point of interest. At this stage, the POIs can be hard coded.

### **Subtasks**

- [x] Choose a CSS framework to build the User Interface with, and ensure that it works properly with Thymeleaf.
- [x] Build the home page of the application, with a navbar and a map component. Ensure that it is responsive and that the Google Maps API for JavaScript is used.
- [x] Study the Google Maps API documentation to review the best methods for popups and creating markers.
- [x] Programmatically create the markers, either in JavaScript or Java, as a test. Create some boilerplate information for each marker.
- [x] Implement an information window or a card that contains the boilerplate information.
