### ISSUE TITLE
Create an API that allows for info about POIs to be stored in a database

### ISSUE THREAD

**Issue by MichaelMale** [MichaelMale/DyfiWildlifeCentre#45]
**Story**: As an administrator, I want to be able to add and edit information about points of interest, so that I can ensure that there is up-to-date information about the wildlife centre.

**Brief detail**: Create an API that allows for information about points of interest to be stored in a database. Program this API to automatically update the Google Maps API with markers and create a page to allow for this to be edited in a textbox and posted to the database. Focus on not having to 'hack' through the HTML or database, similar to a CMS. Worst case: use something like WordPress headless.

### **Subtasks**

- [x] Start constructing the API components in Spring, making a RESTful API. This will be the bulk of the project and it may be better to move this down into different tasks.
- [x] Ensure that the API automatically refreshes the Google Maps API with markers
- [x] Create a page to allow POIs to be edited in a textbox and posted to the database.
- [x] Assess prebuilt implementations should there be a worst case scenario.
