### ISSUE TITLE
Refactoring of information popups

### ISSUE THREAD

**Issue by MichaelMale** [MichaelMale/DyfiWildlifeCentre#46]
**Story**: As a visitor, I want to be able to be told about what the wildlife centre is doing, so that I can get more of a feel and be able to appreciate the area around me.

**Brief detail**: Re-visit the interface created in task #44 to ensure that the information popup is easy to present to someone. Ensure that the interface is easily-readable, for example by having marker clusters. Consider performing user surveys and informal user testing with friends, and even the customer if possible.

### **Subtasks**

- [x] Perform refactoring of #44 and #45 
- [x] Make the information popups created in previous tasks easily readable by assessing the font and thinking about the user experience.
- [x] Research marker clusters and implement them to make markers easier to follow.
- [x] Create basic user surveys and have friends/classmates look at the frontend and suggest any possible improvements.
- [x] Assess the possibility of deliverig a prototype to the customer and having their feedback.
