### ISSUE TITLE
Create an authentication method

### ISSUE THREAD

**Issue by MichaelMale** [MichaelMale/DyfiWildlifeCentre#47]
**Story**: As an administrator, I want to be able to login to an authenticated administration panel, so that I can ensure that only authorised people can change information about the points of interest.

**Brief detail**: Re-visit the interface created in #45 and use a simple authentication algorithm, such as OAuth 2.0 This should include some sort of user/password table and the ability to create new users. It does not necessarily have to have enterprise-grade encryption but should be taken seriously enough to disallow any simple attacks on the web server.

### **Subtasks**

- [x] Research OAuth 2.0 and its applicability to Spring
- [ ] Create a user table where one can login with a username and password
- [ ] Implement cookies (keeping in mind European legislation) or something else to remember a password.
- [ ] Test the encryption with some sort of publicly available penetration testing algorithm.
