### ISSUE TITLE
Create a list of filters

### ISSUE THREAD

**Issue by MichaelMale** [MichaelMale/DyfiWildlifeCentre#48]
**Story**: As a volunteer, I want to be able to filter the map by different defining features, and also press a button in case I go too far from the centre.

**Brief detail**: Create a list of filters that can be selected by the volunteer on the main screen. This will filter out some markers based upon specific boolean values. Will require some further spike work through online tutorials

### **Subtasks**

- [x] Review information on filtering through the Google Maps JavaScript API.
- [x] Refactor the POI class to include booleans such as isTransport, isBusiness and isWildlife.
- [x] Create filtering code and ensure it is test-driven.
