### ISSUE TITLE
Allow for addresses to be entered and geocoded into coordinates

### ISSUE THREAD

**Issue by MichaelMale** [MichaelMale/DyfiWildlifeCentre#49]
**Story**: As a visitor, I want to be able to find out about local businesses that are featured in the application, so that I can get more a feel for what is around the wildlife centre, and potentially visit some interesting businesses.

**Brief detail**: In the admin panel, allow for addresses to be entered and geocoded into coordinates, so that local businesses and places such as educational institutions can be added.

### **Subtasks**

- [x] Implement Google's geocoding API.
- [x] Refactor admin panel to include an address field, which automatically populates the coordinates field.
- [x] Test this using various local businesses around the area.
