### ISSUE TITLE
Make the application bilingual

### ISSUE THREAD

**Issue by MichaelMale** [MichaelMale/DyfiWildlifeCentre#50]
**Story**: As a volunteer, I want the ability to showcase the information in both the medium of English and of Welsh, so that I can accommodate for all people who visit the centre, regardless of their preferred language.

**Brief detail**: Enable I18N internationalisation, creating a basic Welsh version of the website. Ensure that the admin panel accepts name and description information in both English and Welsh. Don't worry about the accuracy of Welsh as this can be corrected by the customer or by Welsh-speaking staff at the University.

### **Subtasks**

- [ ] Research I18N in relation to Spring
- [ ] Create fields for the POIs for the Welsh and English name and description
- [ ] Create a button to toggle between English and Welsh
