### ISSUE TITLE
Implement image uploads

### ISSUE THREAD

**Issue by MichaelMale** [MichaelMale/DyfiWildlifeCentre#51]
**Story**: As an administrator, I want to be able to add images to different points of interest, so that I'll be able to show a visual representation of the point of interest.

**Brief detail**: Include the ability to upload images to the web server, or, failing that, hotlink images. Have them show up with each POI. A card component could be useful for this.

### **Subtasks**

- [x] Look into whether an InfoWindow or whatever implementation was done can take a card.
- [ ] Look into how to upload an image to a Spring server or just allow URLs.
- [ ] Implement copyright warnings.
- [ ] Ensure that image is shown with the correct POI.
- [ ] Ensure that the image is persistent.
